import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { Db } from '../db/open.js';
import { buildPublicPayload, type PublicPayload } from './payload.js';

const here = dirname(fileURLToPath(import.meta.url));
const TEMPLATE = join(here, 'template.html');

export interface PublishResult {
  wrote: boolean;
  pushed: boolean;
  reason: string;
}

/** Owner/name of the GitHub repo the site is published from. */
export function repoSlug(run = git): string | null {
  try {
    const url = run(['remote', 'get-url', 'origin']).trim();
    const m = /github\.com[:/]([^/]+\/[^/.]+)(\.git)?$/.exec(url);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

const git = (args: string[], cwd?: string): string =>
  execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], cwd });

/**
 * Render the public page from the database.
 *
 * The payload is inlined into the HTML rather than fetched as a sibling JSON
 * file: one request, and no second URL sitting there to be indexed or scraped
 * on its own.
 */
export function renderSite(
  db: Db, now: number, outDir: string, slug: string | null,
): { changed: boolean } {
  const payload = buildPublicPayload(db, now);
  const json = JSON.stringify(payload);

  // Skip the write entirely when only the timestamp moved. Every ingest and
  // every pull calls this, so without it the repo would collect a commit per
  // run that changed nothing but generatedAt.
  const indexPath = join(outDir, 'index.html');
  if (samePayload(indexPath, payload)) return { changed: false };

  const html = readFileSync(TEMPLATE, 'utf8')
    .replace('__PAYLOAD__', json)
    .replace(/__REPO__/g, slug ?? '');

  mkdirSync(outDir, { recursive: true });
  // Clear any previous build, including the retired synthetic demo's api/ files.
  for (const stale of ['api', 'demo-config.js']) {
    rmSync(join(outDir, stale), { recursive: true, force: true });
  }
  writeFileSync(indexPath, html);
  writeFileSync(join(outDir, '.nojekyll'), '');
  return { changed: true };
}

/** Is the already-published page carrying the same data, timestamp aside? */
function samePayload(indexPath: string, next: PublicPayload): boolean {
  let prev: PublicPayload;
  try {
    const m = /const D = (\{[\s\S]*?\});\nconst REPO/.exec(readFileSync(indexPath, 'utf8'));
    if (!m) return false;
    prev = JSON.parse(m[1]) as PublicPayload;
  } catch {
    return false;
  }
  const strip = (p: PublicPayload) => JSON.stringify({ ...p, generatedAt: 0 });
  return strip(prev) === strip(next);
}

/**
 * Rebuild the public page and push it if anything changed.
 *
 * Called after every ingest and after every API pull, so the site tracks the
 * data with no command typed. Safe to run unattended because
 * buildPublicPayload is a whitelist and tests/publish/noNames.test.ts proves
 * no name can reach it.
 *
 * Never throws: a failed push must not take down the ingest that triggered it.
 */
export function publish(db: Db, now: number, opts: { outDir?: string; push?: boolean } = {}): PublishResult {
  const outDir = opts.outDir ?? 'docs';
  const slug = repoSlug();
  let changed: boolean;
  try {
    changed = renderSite(db, now, outDir, slug).changed;
  } catch (err) {
    return { wrote: false, pushed: false, reason: `render failed: ${msg(err)}` };
  }
  if (!changed) return { wrote: false, pushed: false, reason: 'no change' };
  if (opts.push === false) return { wrote: true, pushed: false, reason: 'built, push not requested' };
  if (!slug) return { wrote: true, pushed: false, reason: 'no github remote' };

  try {
    // Nothing to do if the numbers did not move. Avoids a commit per ingest.
    const dirty = git(['status', '--porcelain', '--', outDir]).trim();
    if (!dirty) return { wrote: true, pushed: false, reason: 'no change' };

    const branch = git(['rev-parse', '--abbrev-ref', 'HEAD']).trim();
    if (branch !== 'main') {
      return { wrote: true, pushed: false, reason: `on branch ${branch}, not pushing` };
    }
    git(['add', '--', outDir]);
    git(['commit', '-m', `chore: publish site (${new Date(now * 1000).toISOString().slice(0, 10)})`,
         '-m', 'Counts and dates only; no names. Generated by npm run publish.']);
    git(['push', 'origin', 'main']);
    return { wrote: true, pushed: true, reason: 'pushed' };
  } catch (err) {
    return { wrote: true, pushed: false, reason: `push failed: ${msg(err)}` };
  }
}

function msg(err: unknown): string {
  if (err && typeof err === 'object') {
    const e = err as { stderr?: Buffer | string; message?: string };
    const se = e.stderr ? String(e.stderr).trim() : '';
    return (se || e.message || 'unknown').split('\n')[0];
  }
  return String(err);
}
